version: '3'
services:
  front_nespolo:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 4200:4200
      - 49153:49153
    #working_dir: /app/angular-nespolo  
    #command: "ng serve --host 0.0.0.0 --disable-host-check"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true